(test
 (name test_mock_eval)
 (libraries dsh-ocaml dsh-ocaml.core dsh-ocaml.harness eio_main))

(test
 (name test_sandbox)
 (libraries dsh-ocaml dsh-ocaml.core dsh-ocaml.harness eio_main))

(test
 (name test_actor)
 (libraries dsh-ocaml dsh-ocaml.core dsh-ocaml.harness eio_main))

(test
 (name test_net)
 (libraries dsh-ocaml dsh-ocaml.core dsh-ocaml.harness eio_main))

(test
 (name test_drop_handler)
 (libraries dsh-ocaml.core eio_main))

(test
 (name test_fetch_codec)
 (libraries dsh-ocaml.core ocagent-protocol))
