/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAgentContinueRouteImport } from './routes/api/agent/continue'
import { Route as ApiAgentCronRouteImport } from './routes/api/agent/cron'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentContinueRoute = ApiAgentContinueRouteImport.update({
  id: '/api/agent/continue',
  path: '/api/agent/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentCronRoute = ApiAgentCronRouteImport.update({
  id: '/api/agent/cron',
  path: '/api/agent/cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent/continue': typeof ApiAgentContinueRoute
  '/api/agent/cron': typeof ApiAgentCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent/continue': typeof ApiAgentContinueRoute
  '/api/agent/cron': typeof ApiAgentCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent/continue': typeof ApiAgentContinueRoute
  '/api/agent/cron': typeof ApiAgentCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/agent/continue' | '/api/agent/cron'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/agent/continue' | '/api/agent/cron'
  id: '__root__' | '/' | '/api/agent/continue' | '/api/agent/cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentContinueRoute: typeof ApiAgentContinueRoute
  ApiAgentCronRoute: typeof ApiAgentCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/continue': {
      id: '/api/agent/continue'
      path: '/api/agent/continue'
      fullPath: '/api/agent/continue'
      preLoaderRoute: typeof ApiAgentContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/cron': {
      id: '/api/agent/cron'
      path: '/api/agent/cron'
      fullPath: '/api/agent/cron'
      preLoaderRoute: typeof ApiAgentCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentContinueRoute: ApiAgentContinueRoute,
  ApiAgentCronRoute: ApiAgentCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
